// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @enum {number}
 */
export namespace fb.sensor_msgs.NavSatStatusConstants{
export enum status_no_fix{
  value= -1
}};

/**
 * @enum {number}
 */
export namespace fb.sensor_msgs.NavSatStatusConstants{
export enum status_fix{
  value= 0
}};

/**
 * @enum {number}
 */
export namespace fb.sensor_msgs.NavSatStatusConstants{
export enum status_sbas_fix{
  value= 1
}};

/**
 * @enum {number}
 */
export namespace fb.sensor_msgs.NavSatStatusConstants{
export enum status_gbas_fix{
  value= 2
}};

/**
 * @enum {number}
 */
export namespace fb.sensor_msgs.NavSatStatusConstants{
export enum service_gps{
  value= 1
}};

/**
 * @enum {number}
 */
export namespace fb.sensor_msgs.NavSatStatusConstants{
export enum service_glonass{
  value= 2
}};

/**
 * @enum {number}
 */
export namespace fb.sensor_msgs.NavSatStatusConstants{
export enum service_compass{
  value= 4
}};

/**
 * @enum {number}
 */
export namespace fb.sensor_msgs.NavSatStatusConstants{
export enum service_galileo{
  value= 8
}};

/**
 * @enum {number}
 */
export namespace fb.sensor_msgs.NavSatFixConstants{
export enum covariance_type_unknown{
  value= 0
}};

/**
 * @enum {number}
 */
export namespace fb.sensor_msgs.NavSatFixConstants{
export enum covariance_type_approximated{
  value= 1
}};

/**
 * @enum {number}
 */
export namespace fb.sensor_msgs.NavSatFixConstants{
export enum covariance_type_diagonal_known{
  value= 2
}};

/**
 * @enum {number}
 */
export namespace fb.sensor_msgs.NavSatFixConstants{
export enum covariance_type_known{
  value= 3
}};

/**
 * @constructor
 */
export namespace fb{
export class MsgMetadata {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns MsgMetadata
 */
__init(i:number, bb:flatbuffers.ByteBuffer):MsgMetadata {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param MsgMetadata= obj
 * @returns MsgMetadata
 */
static getRootAsMsgMetadata(bb:flatbuffers.ByteBuffer, obj?:MsgMetadata):MsgMetadata {
  return (obj || new MsgMetadata()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param MsgMetadata= obj
 * @returns MsgMetadata
 */
static getSizePrefixedRootAsMsgMetadata(bb:flatbuffers.ByteBuffer, obj?:MsgMetadata):MsgMetadata {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new MsgMetadata()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
type():string|null
type(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
type(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
topic():string|null
topic(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
topic(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startMsgMetadata(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset typeOffset
 */
static addType(builder:flatbuffers.Builder, typeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, typeOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset topicOffset
 */
static addTopic(builder:flatbuffers.Builder, topicOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, topicOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endMsgMetadata(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createMsgMetadata(builder:flatbuffers.Builder, typeOffset:flatbuffers.Offset, topicOffset:flatbuffers.Offset):flatbuffers.Offset {
  MsgMetadata.startMsgMetadata(builder);
  MsgMetadata.addType(builder, typeOffset);
  MsgMetadata.addTopic(builder, topicOffset);
  return MsgMetadata.endMsgMetadata(builder);
}
}
}
/**
 * @constructor
 */
export namespace fb{
export class MsgWithMetadata {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns MsgWithMetadata
 */
__init(i:number, bb:flatbuffers.ByteBuffer):MsgWithMetadata {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param MsgWithMetadata= obj
 * @returns MsgWithMetadata
 */
static getRootAsMsgWithMetadata(bb:flatbuffers.ByteBuffer, obj?:MsgWithMetadata):MsgWithMetadata {
  return (obj || new MsgWithMetadata()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param MsgWithMetadata= obj
 * @returns MsgWithMetadata
 */
static getSizePrefixedRootAsMsgWithMetadata(bb:flatbuffers.ByteBuffer, obj?:MsgWithMetadata):MsgWithMetadata {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new MsgWithMetadata()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param fb.MsgMetadata= obj
 * @returns fb.MsgMetadata|null
 */
_metadata(obj?:fb.MsgMetadata):fb.MsgMetadata|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new fb.MsgMetadata()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startMsgWithMetadata(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset _metadataOffset
 */
static add_Metadata(builder:flatbuffers.Builder, _metadataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, _metadataOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endMsgWithMetadata(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createMsgWithMetadata(builder:flatbuffers.Builder, _metadataOffset:flatbuffers.Offset):flatbuffers.Offset {
  MsgWithMetadata.startMsgWithMetadata(builder);
  MsgWithMetadata.add_Metadata(builder, _metadataOffset);
  return MsgWithMetadata.endMsgWithMetadata(builder);
}
}
}
/**
 * @constructor
 */
export namespace fb{
export class RosTime {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns RosTime
 */
__init(i:number, bb:flatbuffers.ByteBuffer):RosTime {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @returns number
 */
secs():number {
  return this.bb!.readUint32(this.bb_pos);
};

/**
 * @returns number
 */
nsecs():number {
  return this.bb!.readUint32(this.bb_pos + 4);
};

/**
 * @param flatbuffers.Builder builder
 * @param number secs
 * @param number nsecs
 * @returns flatbuffers.Offset
 */
static createRosTime(builder:flatbuffers.Builder, secs: number, nsecs: number):flatbuffers.Offset {
  builder.prep(4, 8);
  builder.writeInt32(nsecs);
  builder.writeInt32(secs);
  return builder.offset();
};

}
}
/**
 * @constructor
 */
export namespace fb{
export class RosDuration {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns RosDuration
 */
__init(i:number, bb:flatbuffers.ByteBuffer):RosDuration {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @returns number
 */
secs():number {
  return this.bb!.readInt32(this.bb_pos);
};

/**
 * @returns number
 */
nsecs():number {
  return this.bb!.readInt32(this.bb_pos + 4);
};

/**
 * @param flatbuffers.Builder builder
 * @param number secs
 * @param number nsecs
 * @returns flatbuffers.Offset
 */
static createRosDuration(builder:flatbuffers.Builder, secs: number, nsecs: number):flatbuffers.Offset {
  builder.prep(4, 8);
  builder.writeInt32(nsecs);
  builder.writeInt32(secs);
  return builder.offset();
};

}
}
/**
 * @constructor
 */
export namespace fb.std_msgs{
export class Header {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns Header
 */
__init(i:number, bb:flatbuffers.ByteBuffer):Header {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Header= obj
 * @returns Header
 */
static getRootAsHeader(bb:flatbuffers.ByteBuffer, obj?:Header):Header {
  return (obj || new Header()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Header= obj
 * @returns Header
 */
static getSizePrefixedRootAsHeader(bb:flatbuffers.ByteBuffer, obj?:Header):Header {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Header()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param fb.MsgMetadata= obj
 * @returns fb.MsgMetadata|null
 */
_metadata(obj?:fb.MsgMetadata):fb.MsgMetadata|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new fb.MsgMetadata()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @returns number
 */
seq():number {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param fb.RosTime= obj
 * @returns fb.RosTime|null
 */
stamp(obj?:fb.RosTime):fb.RosTime|null {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new fb.RosTime()).__init(this.bb_pos + offset, this.bb!) : null;
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
frameId():string|null
frameId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
frameId(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startHeader(builder:flatbuffers.Builder) {
  builder.startObject(4);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset _metadataOffset
 */
static add_Metadata(builder:flatbuffers.Builder, _metadataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, _metadataOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param number seq
 */
static addSeq(builder:flatbuffers.Builder, seq:number) {
  builder.addFieldInt32(1, seq, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset stampOffset
 */
static addStamp(builder:flatbuffers.Builder, stampOffset:flatbuffers.Offset) {
  builder.addFieldStruct(2, stampOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset frameIdOffset
 */
static addFrameId(builder:flatbuffers.Builder, frameIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, frameIdOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endHeader(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createHeader(builder:flatbuffers.Builder, _metadataOffset:flatbuffers.Offset, seq:number, stampOffset:flatbuffers.Offset, frameIdOffset:flatbuffers.Offset):flatbuffers.Offset {
  Header.startHeader(builder);
  Header.add_Metadata(builder, _metadataOffset);
  Header.addSeq(builder, seq);
  Header.addStamp(builder, stampOffset);
  Header.addFrameId(builder, frameIdOffset);
  return Header.endHeader(builder);
}
}
}
/**
 * @constructor
 */
export namespace fb.sensor_msgs{
export class NavSatStatus {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns NavSatStatus
 */
__init(i:number, bb:flatbuffers.ByteBuffer):NavSatStatus {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param NavSatStatus= obj
 * @returns NavSatStatus
 */
static getRootAsNavSatStatus(bb:flatbuffers.ByteBuffer, obj?:NavSatStatus):NavSatStatus {
  return (obj || new NavSatStatus()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param NavSatStatus= obj
 * @returns NavSatStatus
 */
static getSizePrefixedRootAsNavSatStatus(bb:flatbuffers.ByteBuffer, obj?:NavSatStatus):NavSatStatus {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new NavSatStatus()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param fb.MsgMetadata= obj
 * @returns fb.MsgMetadata|null
 */
_metadata(obj?:fb.MsgMetadata):fb.MsgMetadata|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new fb.MsgMetadata()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @returns number
 */
status():number {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : 0;
};

/**
 * @returns number
 */
service():number {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
};

/**
 * @param flatbuffers.Builder builder
 */
static startNavSatStatus(builder:flatbuffers.Builder) {
  builder.startObject(3);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset _metadataOffset
 */
static add_Metadata(builder:flatbuffers.Builder, _metadataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, _metadataOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param number status
 */
static addStatus(builder:flatbuffers.Builder, status:number) {
  builder.addFieldInt8(1, status, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param number service
 */
static addService(builder:flatbuffers.Builder, service:number) {
  builder.addFieldInt16(2, service, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endNavSatStatus(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createNavSatStatus(builder:flatbuffers.Builder, _metadataOffset:flatbuffers.Offset, status:number, service:number):flatbuffers.Offset {
  NavSatStatus.startNavSatStatus(builder);
  NavSatStatus.add_Metadata(builder, _metadataOffset);
  NavSatStatus.addStatus(builder, status);
  NavSatStatus.addService(builder, service);
  return NavSatStatus.endNavSatStatus(builder);
}
}
}
/**
 * @constructor
 */
export namespace fb.sensor_msgs{
export class NavSatFix {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns NavSatFix
 */
__init(i:number, bb:flatbuffers.ByteBuffer):NavSatFix {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param NavSatFix= obj
 * @returns NavSatFix
 */
static getRootAsNavSatFix(bb:flatbuffers.ByteBuffer, obj?:NavSatFix):NavSatFix {
  return (obj || new NavSatFix()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param NavSatFix= obj
 * @returns NavSatFix
 */
static getSizePrefixedRootAsNavSatFix(bb:flatbuffers.ByteBuffer, obj?:NavSatFix):NavSatFix {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new NavSatFix()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param fb.MsgMetadata= obj
 * @returns fb.MsgMetadata|null
 */
_metadata(obj?:fb.MsgMetadata):fb.MsgMetadata|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new fb.MsgMetadata()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @param fb.std_msgs.Header= obj
 * @returns fb.std_msgs.Header|null
 */
header(obj?:fb.std_msgs.Header):fb.std_msgs.Header|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new fb.std_msgs.Header()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @param fb.sensor_msgs.NavSatStatus= obj
 * @returns fb.sensor_msgs.NavSatStatus|null
 */
status(obj?:fb.sensor_msgs.NavSatStatus):fb.sensor_msgs.NavSatStatus|null {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new fb.sensor_msgs.NavSatStatus()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @returns number
 */
latitude():number {
  var offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
};

/**
 * @returns number
 */
longitude():number {
  var offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
};

/**
 * @returns number
 */
altitude():number {
  var offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
};

/**
 * @param number index
 * @returns number
 */
positionCovariance(index: number):number|null {
  var offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readFloat64(this.bb!.__vector(this.bb_pos + offset) + index * 8) : 0;
};

/**
 * @returns number
 */
positionCovarianceLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns Float64Array
 */
positionCovarianceArray():Float64Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? new Float64Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @returns number
 */
positionCovarianceType():number {
  var offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
};

/**
 * @param flatbuffers.Builder builder
 */
static startNavSatFix(builder:flatbuffers.Builder) {
  builder.startObject(8);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset _metadataOffset
 */
static add_Metadata(builder:flatbuffers.Builder, _metadataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, _metadataOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset headerOffset
 */
static addHeader(builder:flatbuffers.Builder, headerOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, headerOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset statusOffset
 */
static addStatus(builder:flatbuffers.Builder, statusOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, statusOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param number latitude
 */
static addLatitude(builder:flatbuffers.Builder, latitude:number) {
  builder.addFieldFloat64(3, latitude, 0.0);
};

/**
 * @param flatbuffers.Builder builder
 * @param number longitude
 */
static addLongitude(builder:flatbuffers.Builder, longitude:number) {
  builder.addFieldFloat64(4, longitude, 0.0);
};

/**
 * @param flatbuffers.Builder builder
 * @param number altitude
 */
static addAltitude(builder:flatbuffers.Builder, altitude:number) {
  builder.addFieldFloat64(5, altitude, 0.0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset positionCovarianceOffset
 */
static addPositionCovariance(builder:flatbuffers.Builder, positionCovarianceOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, positionCovarianceOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<number> data
 * @returns flatbuffers.Offset
 */
static createPositionCovarianceVector(builder:flatbuffers.Builder, data:number[] | Uint8Array):flatbuffers.Offset {
  builder.startVector(8, data.length, 8);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addFloat64(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startPositionCovarianceVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(8, numElems, 8);
};

/**
 * @param flatbuffers.Builder builder
 * @param number positionCovarianceType
 */
static addPositionCovarianceType(builder:flatbuffers.Builder, positionCovarianceType:number) {
  builder.addFieldInt8(7, positionCovarianceType, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endNavSatFix(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createNavSatFix(builder:flatbuffers.Builder, _metadataOffset:flatbuffers.Offset, headerOffset:flatbuffers.Offset, statusOffset:flatbuffers.Offset, latitude:number, longitude:number, altitude:number, positionCovarianceOffset:flatbuffers.Offset, positionCovarianceType:number):flatbuffers.Offset {
  NavSatFix.startNavSatFix(builder);
  NavSatFix.add_Metadata(builder, _metadataOffset);
  NavSatFix.addHeader(builder, headerOffset);
  NavSatFix.addStatus(builder, statusOffset);
  NavSatFix.addLatitude(builder, latitude);
  NavSatFix.addLongitude(builder, longitude);
  NavSatFix.addAltitude(builder, altitude);
  NavSatFix.addPositionCovariance(builder, positionCovarianceOffset);
  NavSatFix.addPositionCovarianceType(builder, positionCovarianceType);
  return NavSatFix.endNavSatFix(builder);
}
}
}
/**
 * @constructor
 */
export namespace fb.amrl_msgs{
export class RobofleetStatus {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns RobofleetStatus
 */
__init(i:number, bb:flatbuffers.ByteBuffer):RobofleetStatus {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param RobofleetStatus= obj
 * @returns RobofleetStatus
 */
static getRootAsRobofleetStatus(bb:flatbuffers.ByteBuffer, obj?:RobofleetStatus):RobofleetStatus {
  return (obj || new RobofleetStatus()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param RobofleetStatus= obj
 * @returns RobofleetStatus
 */
static getSizePrefixedRootAsRobofleetStatus(bb:flatbuffers.ByteBuffer, obj?:RobofleetStatus):RobofleetStatus {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RobofleetStatus()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param fb.MsgMetadata= obj
 * @returns fb.MsgMetadata|null
 */
_metadata(obj?:fb.MsgMetadata):fb.MsgMetadata|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new fb.MsgMetadata()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
status():string|null
status(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
status(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns boolean
 */
isOk():boolean {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
};

/**
 * @returns number
 */
batteryLevel():number {
  var offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
location():string|null
location(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
location(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startRobofleetStatus(builder:flatbuffers.Builder) {
  builder.startObject(5);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset _metadataOffset
 */
static add_Metadata(builder:flatbuffers.Builder, _metadataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, _metadataOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset statusOffset
 */
static addStatus(builder:flatbuffers.Builder, statusOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, statusOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param boolean isOk
 */
static addIsOk(builder:flatbuffers.Builder, isOk:boolean) {
  builder.addFieldInt8(2, +isOk, +false);
};

/**
 * @param flatbuffers.Builder builder
 * @param number batteryLevel
 */
static addBatteryLevel(builder:flatbuffers.Builder, batteryLevel:number) {
  builder.addFieldFloat32(3, batteryLevel, 0.0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset locationOffset
 */
static addLocation(builder:flatbuffers.Builder, locationOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, locationOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endRobofleetStatus(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createRobofleetStatus(builder:flatbuffers.Builder, _metadataOffset:flatbuffers.Offset, statusOffset:flatbuffers.Offset, isOk:boolean, batteryLevel:number, locationOffset:flatbuffers.Offset):flatbuffers.Offset {
  RobofleetStatus.startRobofleetStatus(builder);
  RobofleetStatus.add_Metadata(builder, _metadataOffset);
  RobofleetStatus.addStatus(builder, statusOffset);
  RobofleetStatus.addIsOk(builder, isOk);
  RobofleetStatus.addBatteryLevel(builder, batteryLevel);
  RobofleetStatus.addLocation(builder, locationOffset);
  return RobofleetStatus.endRobofleetStatus(builder);
}
}
}
