// automatically generated by the FlatBuffers compiler, do not modify

import {flatbuffers} from "flatbuffers";

/**
 * @const
 * @namespace
 */
var fb = fb || {};

/**
 * @const
 * @namespace
 */
fb.sensor_msgs = fb.sensor_msgs || {};

/**
 * @const
 * @namespace
 */
fb.std_msgs = fb.std_msgs || {};

/**
 * @constructor
 */
fb.MsgMetadata = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {fb.MsgMetadata}
 */
fb.MsgMetadata.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {fb.MsgMetadata=} obj
 * @returns {fb.MsgMetadata}
 */
fb.MsgMetadata.getRootAsMsgMetadata = function(bb, obj) {
  return (obj || new fb.MsgMetadata).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {fb.MsgMetadata=} obj
 * @returns {fb.MsgMetadata}
 */
fb.MsgMetadata.getSizePrefixedRootAsMsgMetadata = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new fb.MsgMetadata).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
fb.MsgMetadata.prototype.topic = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
fb.MsgMetadata.startMsgMetadata = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} topicOffset
 */
fb.MsgMetadata.addTopic = function(builder, topicOffset) {
  builder.addFieldOffset(0, topicOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
fb.MsgMetadata.endMsgMetadata = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} topicOffset
 * @returns {flatbuffers.Offset}
 */
fb.MsgMetadata.createMsgMetadata = function(builder, topicOffset) {
  fb.MsgMetadata.startMsgMetadata(builder);
  fb.MsgMetadata.addTopic(builder, topicOffset);
  return fb.MsgMetadata.endMsgMetadata(builder);
}

/**
 * @constructor
 */
fb.MsgWithMetadata = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {fb.MsgWithMetadata}
 */
fb.MsgWithMetadata.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {fb.MsgWithMetadata=} obj
 * @returns {fb.MsgWithMetadata}
 */
fb.MsgWithMetadata.getRootAsMsgWithMetadata = function(bb, obj) {
  return (obj || new fb.MsgWithMetadata).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {fb.MsgWithMetadata=} obj
 * @returns {fb.MsgWithMetadata}
 */
fb.MsgWithMetadata.getSizePrefixedRootAsMsgWithMetadata = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new fb.MsgWithMetadata).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {fb.MsgMetadata=} obj
 * @returns {fb.MsgMetadata|null}
 */
fb.MsgWithMetadata.prototype._metadata = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new fb.MsgMetadata).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
fb.MsgWithMetadata.startMsgWithMetadata = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} _metadataOffset
 */
fb.MsgWithMetadata.add_Metadata = function(builder, _metadataOffset) {
  builder.addFieldOffset(0, _metadataOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
fb.MsgWithMetadata.endMsgWithMetadata = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} _metadataOffset
 * @returns {flatbuffers.Offset}
 */
fb.MsgWithMetadata.createMsgWithMetadata = function(builder, _metadataOffset) {
  fb.MsgWithMetadata.startMsgWithMetadata(builder);
  fb.MsgWithMetadata.add_Metadata(builder, _metadataOffset);
  return fb.MsgWithMetadata.endMsgWithMetadata(builder);
}

/**
 * @constructor
 */
fb.RosTime = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {fb.RosTime}
 */
fb.RosTime.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @returns {number}
 */
fb.RosTime.prototype.secs = function() {
  return this.bb.readUint32(this.bb_pos);
};

/**
 * @returns {number}
 */
fb.RosTime.prototype.nsecs = function() {
  return this.bb.readUint32(this.bb_pos + 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} secs
 * @param {number} nsecs
 * @returns {flatbuffers.Offset}
 */
fb.RosTime.createRosTime = function(builder, secs, nsecs) {
  builder.prep(4, 8);
  builder.writeInt32(nsecs);
  builder.writeInt32(secs);
  return builder.offset();
};

/**
 * @constructor
 */
fb.RosDuration = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {fb.RosDuration}
 */
fb.RosDuration.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @returns {number}
 */
fb.RosDuration.prototype.secs = function() {
  return this.bb.readInt32(this.bb_pos);
};

/**
 * @returns {number}
 */
fb.RosDuration.prototype.nsecs = function() {
  return this.bb.readInt32(this.bb_pos + 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} secs
 * @param {number} nsecs
 * @returns {flatbuffers.Offset}
 */
fb.RosDuration.createRosDuration = function(builder, secs, nsecs) {
  builder.prep(4, 8);
  builder.writeInt32(nsecs);
  builder.writeInt32(secs);
  return builder.offset();
};

/**
 * @constructor
 */
fb.std_msgs.Header = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {fb.std_msgs.Header}
 */
fb.std_msgs.Header.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {fb.std_msgs.Header=} obj
 * @returns {fb.std_msgs.Header}
 */
fb.std_msgs.Header.getRootAsHeader = function(bb, obj) {
  return (obj || new fb.std_msgs.Header).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {fb.std_msgs.Header=} obj
 * @returns {fb.std_msgs.Header}
 */
fb.std_msgs.Header.getSizePrefixedRootAsHeader = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new fb.std_msgs.Header).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {fb.MsgMetadata=} obj
 * @returns {fb.MsgMetadata|null}
 */
fb.std_msgs.Header.prototype._metadata = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new fb.MsgMetadata).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @returns {number}
 */
fb.std_msgs.Header.prototype.seq = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param {fb.RosTime=} obj
 * @returns {fb.RosTime|null}
 */
fb.std_msgs.Header.prototype.stamp = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? (obj || new fb.RosTime).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
fb.std_msgs.Header.prototype.frameId = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
fb.std_msgs.Header.startHeader = function(builder) {
  builder.startObject(4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} _metadataOffset
 */
fb.std_msgs.Header.add_Metadata = function(builder, _metadataOffset) {
  builder.addFieldOffset(0, _metadataOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} seq
 */
fb.std_msgs.Header.addSeq = function(builder, seq) {
  builder.addFieldInt32(1, seq, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} stampOffset
 */
fb.std_msgs.Header.addStamp = function(builder, stampOffset) {
  builder.addFieldStruct(2, stampOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} frameIdOffset
 */
fb.std_msgs.Header.addFrameId = function(builder, frameIdOffset) {
  builder.addFieldOffset(3, frameIdOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
fb.std_msgs.Header.endHeader = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} _metadataOffset
 * @param {number} seq
 * @param {flatbuffers.Offset} stampOffset
 * @param {flatbuffers.Offset} frameIdOffset
 * @returns {flatbuffers.Offset}
 */
fb.std_msgs.Header.createHeader = function(builder, _metadataOffset, seq, stampOffset, frameIdOffset) {
  fb.std_msgs.Header.startHeader(builder);
  fb.std_msgs.Header.add_Metadata(builder, _metadataOffset);
  fb.std_msgs.Header.addSeq(builder, seq);
  fb.std_msgs.Header.addStamp(builder, stampOffset);
  fb.std_msgs.Header.addFrameId(builder, frameIdOffset);
  return fb.std_msgs.Header.endHeader(builder);
}

/**
 * @constructor
 */
fb.sensor_msgs.NavSatStatusConstants = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {fb.sensor_msgs.NavSatStatusConstants}
 */
fb.sensor_msgs.NavSatStatusConstants.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {fb.sensor_msgs.NavSatStatusConstants=} obj
 * @returns {fb.sensor_msgs.NavSatStatusConstants}
 */
fb.sensor_msgs.NavSatStatusConstants.getRootAsNavSatStatusConstants = function(bb, obj) {
  return (obj || new fb.sensor_msgs.NavSatStatusConstants).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {fb.sensor_msgs.NavSatStatusConstants=} obj
 * @returns {fb.sensor_msgs.NavSatStatusConstants}
 */
fb.sensor_msgs.NavSatStatusConstants.getSizePrefixedRootAsNavSatStatusConstants = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new fb.sensor_msgs.NavSatStatusConstants).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
fb.sensor_msgs.NavSatStatusConstants.prototype.statusNoFix = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readInt8(this.bb_pos + offset) : -1;
};

/**
 * @returns {number}
 */
fb.sensor_msgs.NavSatStatusConstants.prototype.statusFix = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readInt8(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
fb.sensor_msgs.NavSatStatusConstants.prototype.statusSbasFix = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readInt8(this.bb_pos + offset) : 1;
};

/**
 * @returns {number}
 */
fb.sensor_msgs.NavSatStatusConstants.prototype.statusGbasFix = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readInt8(this.bb_pos + offset) : 2;
};

/**
 * @returns {number}
 */
fb.sensor_msgs.NavSatStatusConstants.prototype.serviceGps = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.readUint16(this.bb_pos + offset) : 1;
};

/**
 * @returns {number}
 */
fb.sensor_msgs.NavSatStatusConstants.prototype.serviceGlonass = function() {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? this.bb.readUint16(this.bb_pos + offset) : 2;
};

/**
 * @returns {number}
 */
fb.sensor_msgs.NavSatStatusConstants.prototype.serviceCompass = function() {
  var offset = this.bb.__offset(this.bb_pos, 16);
  return offset ? this.bb.readUint16(this.bb_pos + offset) : 4;
};

/**
 * @returns {number}
 */
fb.sensor_msgs.NavSatStatusConstants.prototype.serviceGalileo = function() {
  var offset = this.bb.__offset(this.bb_pos, 18);
  return offset ? this.bb.readUint16(this.bb_pos + offset) : 8;
};

/**
 * @param {flatbuffers.Builder} builder
 */
fb.sensor_msgs.NavSatStatusConstants.startNavSatStatusConstants = function(builder) {
  builder.startObject(8);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} statusNoFix
 */
fb.sensor_msgs.NavSatStatusConstants.addStatusNoFix = function(builder, statusNoFix) {
  builder.addFieldInt8(0, statusNoFix, -1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} statusFix
 */
fb.sensor_msgs.NavSatStatusConstants.addStatusFix = function(builder, statusFix) {
  builder.addFieldInt8(1, statusFix, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} statusSbasFix
 */
fb.sensor_msgs.NavSatStatusConstants.addStatusSbasFix = function(builder, statusSbasFix) {
  builder.addFieldInt8(2, statusSbasFix, 1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} statusGbasFix
 */
fb.sensor_msgs.NavSatStatusConstants.addStatusGbasFix = function(builder, statusGbasFix) {
  builder.addFieldInt8(3, statusGbasFix, 2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} serviceGps
 */
fb.sensor_msgs.NavSatStatusConstants.addServiceGps = function(builder, serviceGps) {
  builder.addFieldInt16(4, serviceGps, 1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} serviceGlonass
 */
fb.sensor_msgs.NavSatStatusConstants.addServiceGlonass = function(builder, serviceGlonass) {
  builder.addFieldInt16(5, serviceGlonass, 2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} serviceCompass
 */
fb.sensor_msgs.NavSatStatusConstants.addServiceCompass = function(builder, serviceCompass) {
  builder.addFieldInt16(6, serviceCompass, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} serviceGalileo
 */
fb.sensor_msgs.NavSatStatusConstants.addServiceGalileo = function(builder, serviceGalileo) {
  builder.addFieldInt16(7, serviceGalileo, 8);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
fb.sensor_msgs.NavSatStatusConstants.endNavSatStatusConstants = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} statusNoFix
 * @param {number} statusFix
 * @param {number} statusSbasFix
 * @param {number} statusGbasFix
 * @param {number} serviceGps
 * @param {number} serviceGlonass
 * @param {number} serviceCompass
 * @param {number} serviceGalileo
 * @returns {flatbuffers.Offset}
 */
fb.sensor_msgs.NavSatStatusConstants.createNavSatStatusConstants = function(builder, statusNoFix, statusFix, statusSbasFix, statusGbasFix, serviceGps, serviceGlonass, serviceCompass, serviceGalileo) {
  fb.sensor_msgs.NavSatStatusConstants.startNavSatStatusConstants(builder);
  fb.sensor_msgs.NavSatStatusConstants.addStatusNoFix(builder, statusNoFix);
  fb.sensor_msgs.NavSatStatusConstants.addStatusFix(builder, statusFix);
  fb.sensor_msgs.NavSatStatusConstants.addStatusSbasFix(builder, statusSbasFix);
  fb.sensor_msgs.NavSatStatusConstants.addStatusGbasFix(builder, statusGbasFix);
  fb.sensor_msgs.NavSatStatusConstants.addServiceGps(builder, serviceGps);
  fb.sensor_msgs.NavSatStatusConstants.addServiceGlonass(builder, serviceGlonass);
  fb.sensor_msgs.NavSatStatusConstants.addServiceCompass(builder, serviceCompass);
  fb.sensor_msgs.NavSatStatusConstants.addServiceGalileo(builder, serviceGalileo);
  return fb.sensor_msgs.NavSatStatusConstants.endNavSatStatusConstants(builder);
}

/**
 * @constructor
 */
fb.sensor_msgs.NavSatStatus = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {fb.sensor_msgs.NavSatStatus}
 */
fb.sensor_msgs.NavSatStatus.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {fb.sensor_msgs.NavSatStatus=} obj
 * @returns {fb.sensor_msgs.NavSatStatus}
 */
fb.sensor_msgs.NavSatStatus.getRootAsNavSatStatus = function(bb, obj) {
  return (obj || new fb.sensor_msgs.NavSatStatus).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {fb.sensor_msgs.NavSatStatus=} obj
 * @returns {fb.sensor_msgs.NavSatStatus}
 */
fb.sensor_msgs.NavSatStatus.getSizePrefixedRootAsNavSatStatus = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new fb.sensor_msgs.NavSatStatus).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {fb.MsgMetadata=} obj
 * @returns {fb.MsgMetadata|null}
 */
fb.sensor_msgs.NavSatStatus.prototype._metadata = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new fb.MsgMetadata).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @returns {number}
 */
fb.sensor_msgs.NavSatStatus.prototype.status = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readInt8(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
fb.sensor_msgs.NavSatStatus.prototype.service = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readUint16(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
fb.sensor_msgs.NavSatStatus.startNavSatStatus = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} _metadataOffset
 */
fb.sensor_msgs.NavSatStatus.add_Metadata = function(builder, _metadataOffset) {
  builder.addFieldOffset(0, _metadataOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} status
 */
fb.sensor_msgs.NavSatStatus.addStatus = function(builder, status) {
  builder.addFieldInt8(1, status, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} service
 */
fb.sensor_msgs.NavSatStatus.addService = function(builder, service) {
  builder.addFieldInt16(2, service, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
fb.sensor_msgs.NavSatStatus.endNavSatStatus = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} _metadataOffset
 * @param {number} status
 * @param {number} service
 * @returns {flatbuffers.Offset}
 */
fb.sensor_msgs.NavSatStatus.createNavSatStatus = function(builder, _metadataOffset, status, service) {
  fb.sensor_msgs.NavSatStatus.startNavSatStatus(builder);
  fb.sensor_msgs.NavSatStatus.add_Metadata(builder, _metadataOffset);
  fb.sensor_msgs.NavSatStatus.addStatus(builder, status);
  fb.sensor_msgs.NavSatStatus.addService(builder, service);
  return fb.sensor_msgs.NavSatStatus.endNavSatStatus(builder);
}

/**
 * @constructor
 */
fb.sensor_msgs.NavSatFixConstants = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {fb.sensor_msgs.NavSatFixConstants}
 */
fb.sensor_msgs.NavSatFixConstants.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {fb.sensor_msgs.NavSatFixConstants=} obj
 * @returns {fb.sensor_msgs.NavSatFixConstants}
 */
fb.sensor_msgs.NavSatFixConstants.getRootAsNavSatFixConstants = function(bb, obj) {
  return (obj || new fb.sensor_msgs.NavSatFixConstants).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {fb.sensor_msgs.NavSatFixConstants=} obj
 * @returns {fb.sensor_msgs.NavSatFixConstants}
 */
fb.sensor_msgs.NavSatFixConstants.getSizePrefixedRootAsNavSatFixConstants = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new fb.sensor_msgs.NavSatFixConstants).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
fb.sensor_msgs.NavSatFixConstants.prototype.covarianceTypeUnknown = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint8(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
fb.sensor_msgs.NavSatFixConstants.prototype.covarianceTypeApproximated = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint8(this.bb_pos + offset) : 1;
};

/**
 * @returns {number}
 */
fb.sensor_msgs.NavSatFixConstants.prototype.covarianceTypeDiagonalKnown = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readUint8(this.bb_pos + offset) : 2;
};

/**
 * @returns {number}
 */
fb.sensor_msgs.NavSatFixConstants.prototype.covarianceTypeKnown = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readUint8(this.bb_pos + offset) : 3;
};

/**
 * @param {flatbuffers.Builder} builder
 */
fb.sensor_msgs.NavSatFixConstants.startNavSatFixConstants = function(builder) {
  builder.startObject(4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} covarianceTypeUnknown
 */
fb.sensor_msgs.NavSatFixConstants.addCovarianceTypeUnknown = function(builder, covarianceTypeUnknown) {
  builder.addFieldInt8(0, covarianceTypeUnknown, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} covarianceTypeApproximated
 */
fb.sensor_msgs.NavSatFixConstants.addCovarianceTypeApproximated = function(builder, covarianceTypeApproximated) {
  builder.addFieldInt8(1, covarianceTypeApproximated, 1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} covarianceTypeDiagonalKnown
 */
fb.sensor_msgs.NavSatFixConstants.addCovarianceTypeDiagonalKnown = function(builder, covarianceTypeDiagonalKnown) {
  builder.addFieldInt8(2, covarianceTypeDiagonalKnown, 2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} covarianceTypeKnown
 */
fb.sensor_msgs.NavSatFixConstants.addCovarianceTypeKnown = function(builder, covarianceTypeKnown) {
  builder.addFieldInt8(3, covarianceTypeKnown, 3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
fb.sensor_msgs.NavSatFixConstants.endNavSatFixConstants = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} covarianceTypeUnknown
 * @param {number} covarianceTypeApproximated
 * @param {number} covarianceTypeDiagonalKnown
 * @param {number} covarianceTypeKnown
 * @returns {flatbuffers.Offset}
 */
fb.sensor_msgs.NavSatFixConstants.createNavSatFixConstants = function(builder, covarianceTypeUnknown, covarianceTypeApproximated, covarianceTypeDiagonalKnown, covarianceTypeKnown) {
  fb.sensor_msgs.NavSatFixConstants.startNavSatFixConstants(builder);
  fb.sensor_msgs.NavSatFixConstants.addCovarianceTypeUnknown(builder, covarianceTypeUnknown);
  fb.sensor_msgs.NavSatFixConstants.addCovarianceTypeApproximated(builder, covarianceTypeApproximated);
  fb.sensor_msgs.NavSatFixConstants.addCovarianceTypeDiagonalKnown(builder, covarianceTypeDiagonalKnown);
  fb.sensor_msgs.NavSatFixConstants.addCovarianceTypeKnown(builder, covarianceTypeKnown);
  return fb.sensor_msgs.NavSatFixConstants.endNavSatFixConstants(builder);
}

/**
 * @constructor
 */
fb.sensor_msgs.NavSatFix = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {fb.sensor_msgs.NavSatFix}
 */
fb.sensor_msgs.NavSatFix.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {fb.sensor_msgs.NavSatFix=} obj
 * @returns {fb.sensor_msgs.NavSatFix}
 */
fb.sensor_msgs.NavSatFix.getRootAsNavSatFix = function(bb, obj) {
  return (obj || new fb.sensor_msgs.NavSatFix).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {fb.sensor_msgs.NavSatFix=} obj
 * @returns {fb.sensor_msgs.NavSatFix}
 */
fb.sensor_msgs.NavSatFix.getSizePrefixedRootAsNavSatFix = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new fb.sensor_msgs.NavSatFix).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {fb.MsgMetadata=} obj
 * @returns {fb.MsgMetadata|null}
 */
fb.sensor_msgs.NavSatFix.prototype._metadata = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new fb.MsgMetadata).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {fb.std_msgs.Header=} obj
 * @returns {fb.std_msgs.Header|null}
 */
fb.sensor_msgs.NavSatFix.prototype.header = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new fb.std_msgs.Header).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {fb.sensor_msgs.NavSatStatus=} obj
 * @returns {fb.sensor_msgs.NavSatStatus|null}
 */
fb.sensor_msgs.NavSatFix.prototype.status = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? (obj || new fb.sensor_msgs.NavSatStatus).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @returns {number}
 */
fb.sensor_msgs.NavSatFix.prototype.latitude = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
};

/**
 * @returns {number}
 */
fb.sensor_msgs.NavSatFix.prototype.longitude = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
};

/**
 * @returns {number}
 */
fb.sensor_msgs.NavSatFix.prototype.altitude = function() {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
};

/**
 * @param {number} index
 * @returns {number}
 */
fb.sensor_msgs.NavSatFix.prototype.positionCovariance = function(index) {
  var offset = this.bb.__offset(this.bb_pos, 16);
  return offset ? this.bb.readFloat64(this.bb.__vector(this.bb_pos + offset) + index * 8) : 0;
};

/**
 * @returns {number}
 */
fb.sensor_msgs.NavSatFix.prototype.positionCovarianceLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 16);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns {Float64Array}
 */
fb.sensor_msgs.NavSatFix.prototype.positionCovarianceArray = function() {
  var offset = this.bb.__offset(this.bb_pos, 16);
  return offset ? new Float64Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @returns {number}
 */
fb.sensor_msgs.NavSatFix.prototype.positionCovarianceType = function() {
  var offset = this.bb.__offset(this.bb_pos, 18);
  return offset ? this.bb.readUint8(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
fb.sensor_msgs.NavSatFix.startNavSatFix = function(builder) {
  builder.startObject(8);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} _metadataOffset
 */
fb.sensor_msgs.NavSatFix.add_Metadata = function(builder, _metadataOffset) {
  builder.addFieldOffset(0, _metadataOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} headerOffset
 */
fb.sensor_msgs.NavSatFix.addHeader = function(builder, headerOffset) {
  builder.addFieldOffset(1, headerOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} statusOffset
 */
fb.sensor_msgs.NavSatFix.addStatus = function(builder, statusOffset) {
  builder.addFieldOffset(2, statusOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} latitude
 */
fb.sensor_msgs.NavSatFix.addLatitude = function(builder, latitude) {
  builder.addFieldFloat64(3, latitude, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} longitude
 */
fb.sensor_msgs.NavSatFix.addLongitude = function(builder, longitude) {
  builder.addFieldFloat64(4, longitude, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} altitude
 */
fb.sensor_msgs.NavSatFix.addAltitude = function(builder, altitude) {
  builder.addFieldFloat64(5, altitude, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} positionCovarianceOffset
 */
fb.sensor_msgs.NavSatFix.addPositionCovariance = function(builder, positionCovarianceOffset) {
  builder.addFieldOffset(6, positionCovarianceOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<number>} data
 * @returns {flatbuffers.Offset}
 */
fb.sensor_msgs.NavSatFix.createPositionCovarianceVector = function(builder, data) {
  builder.startVector(8, data.length, 8);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addFloat64(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
fb.sensor_msgs.NavSatFix.startPositionCovarianceVector = function(builder, numElems) {
  builder.startVector(8, numElems, 8);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} positionCovarianceType
 */
fb.sensor_msgs.NavSatFix.addPositionCovarianceType = function(builder, positionCovarianceType) {
  builder.addFieldInt8(7, positionCovarianceType, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
fb.sensor_msgs.NavSatFix.endNavSatFix = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} _metadataOffset
 * @param {flatbuffers.Offset} headerOffset
 * @param {flatbuffers.Offset} statusOffset
 * @param {number} latitude
 * @param {number} longitude
 * @param {number} altitude
 * @param {flatbuffers.Offset} positionCovarianceOffset
 * @param {number} positionCovarianceType
 * @returns {flatbuffers.Offset}
 */
fb.sensor_msgs.NavSatFix.createNavSatFix = function(builder, _metadataOffset, headerOffset, statusOffset, latitude, longitude, altitude, positionCovarianceOffset, positionCovarianceType) {
  fb.sensor_msgs.NavSatFix.startNavSatFix(builder);
  fb.sensor_msgs.NavSatFix.add_Metadata(builder, _metadataOffset);
  fb.sensor_msgs.NavSatFix.addHeader(builder, headerOffset);
  fb.sensor_msgs.NavSatFix.addStatus(builder, statusOffset);
  fb.sensor_msgs.NavSatFix.addLatitude(builder, latitude);
  fb.sensor_msgs.NavSatFix.addLongitude(builder, longitude);
  fb.sensor_msgs.NavSatFix.addAltitude(builder, altitude);
  fb.sensor_msgs.NavSatFix.addPositionCovariance(builder, positionCovarianceOffset);
  fb.sensor_msgs.NavSatFix.addPositionCovarianceType(builder, positionCovarianceType);
  return fb.sensor_msgs.NavSatFix.endNavSatFix(builder);
}

// Exports for ECMAScript6 Modules
export {fb};
